name: Python

<<<<<<< HEAD
on:
  push:
    - main
=======
on: 
  push:
    branches:
      - main
>>>>>>> dd3d6b2 (stuff)

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FOO: "Bar"  # Your existing environment variable
      BAZZ: ${{ secrets.bazz }}  # Accessing the 'bazz' secret
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        pytest tests.py  # Run pytest on your test file
    - name: Use BAZZ secret
      run: |
        echo "Secret BAZZ is $BAZZ"
