name Python application test with GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FOO: "Bar"  # Setting the environment variable 'FOO'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Test with pytest
      run: |
        pytest tests.py  # Run pytest on your test file
:
